fix "m2net/Request.cs(99,86): error CS0246: The type or namespace name `TnetString' could not be found. Are you missing a using directive or an assembly reference?" using Makefile